config/routes.rb
Rails.application.routes.draw do
  root 'things#index'

  resources :things do
    collection do
      get :search
    end
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    class_attribute :searchable_columns_array, :stemmer_klass, 
                    :word_breaker_klass

    has_many :stem_joins, as: :searchable, dependent: :delete_all
    has_many :stems, through: :stem_joins

    after_save :update_stems

    word_breaker DefaultWordBreaker
    stemmer      DefaultStemmer
  end

  def update_stems
    if self.searchable_columns_array.nil? || self.searchable_columns_array.empty?
      raise "Define searchable columns using #searchable_columns class method"
    end

    Stem.transaction do
      self.stem_joins.delete_all

      words = searchable_values
              .flat_map { |value| self.class.word_breaker_klass.new(value).split }
              .map { |word| self.class.stemmer_klass.stem(word) }
              .uniq

      words.each do |word|
        stem = Stem.find_or_create_by(word: word)
        self.stem_joins.find_or_create_by(searchable_type: self.class.name, searchable_id: self.id, stem_id: stem.id)
      end
    end

  end

  private

  def searchable_values
    self.attributes.symbolize_keys
    .values_at(*Array(self.searchable_columns_array))
  end

  module ClassMethods
    def searchable_columns(*columns)
      self.searchable_columns_array = columns
    end

    def stemmer(klass)
      self.stemmer_klass = klass
    end

    def word_breaker(klass)
      self.word_breaker_klass = klass
    end

    def search(query, options = {})
      stems = prepare_stems(query)

      where("id IN (#{stems_query(stems[:included], stems[:excluded])})")
    end

    def prepare_stems(query)
      words = query.split(/ +/)
      results = {
        excluded: [],
        included: []
      }

      words.each do |word|
        if word.first == "-"
          results[:excluded] << self.stemmer_klass.stem(word[1..-1])
        else
          results[:included] << self.stemmer_klass.stem(word)
        end
      end

      results
    end

    def stems_query(inclusions, exclusions)
      queries = []
      
      queries << inclusions.map do |word|
        word_query(word)
      end.join(" INTERSECT ")

      if exclusions.any?
        queries << "EXCEPT"
        queries << exclusions.map do |word|
          word_query(word)
        end.join(" EXCEPT ")
      end

      queries.join(" ")
    end

    def word_query(word)
      Stem.select(:searchable_id)
        .joins(:stem_joins)
        .where("stem_joins.searchable_type = ? AND stems.word = ?", self.name, word)
        .to_sql
    end
  end
end

app/models/stem.rb
class Stem < ActiveRecord::Base
  has_many :stem_joins
  belongs_to :searchable, polymorphic: true

  has_many :things, through: :stem_joins, source: :searchable, source_type: 'Thing'
end

app/models/stem_join.rb
class StemJoin < ActiveRecord::Base
  belongs_to :searchable, polymorphic: true
  belongs_to :stem
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  include Searchable

  searchable_columns :content

  stemmer DefaultStemmer
  word_breaker DefaultWordBreaker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def index
    @things = Thing.order("created_at DESC").page(params[:page])
  end

  def search
    @things = Thing.search(params[:query]).page(params[:page])
  end

  def new
    @thing = Thing.new
  end

  def create
    @thing = Thing.new
    @thing.content = params[:thing][:content]
    if @thing.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
  def highlighted_content(content, query)
    return content if query.nil?
    stems = Thing.prepare_stems(query)[:included]
    words = Thing.word_breaker_klass.new(content).split

    conversions = Hash[words.map { |word| [Thing.stemmer_klass.stem(word), word] }].slice(*stems)
    conversions.values.each do |word|
      content.gsub!(word) do |highlight| 
        content_tag(:span, highlight, class: 'highlight')
      end
    end
    content
  end
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Full Text Search"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/modernizr"
  = csrf_meta_tag

body
  nav.top-bar data-topbar=true
    ul.title-area
      li.name
        h1 = link_to "FTS Demo", root_path

    section.top-bar-section
      ul.right
        li.active = link_to "Add a thing", new_thing_path
    section.top-bar-section
      ul.left
        li.has-form
          .row
            .large-12.small-12.columns
              = simple_form_for Thing.new, url: search_things_path, method: :get do |f|
                = f.input :content, as: :string, label: false, \
                  placeholder: "Find things", input_html: { name: "query", value: params[:query]}
  .row
    .large-12.columns
      == yield

  = javascript_include_tag "application"

app/views/things/_thing.slim
.row
  .large-12.columns
    span.label.secondary = l thing.created_at
  .large-12.columns
    p == highlighted_content(thing.content, params[:query])

app/views/things/index.slim
h1 List all the things!

- if @things.any?
  = paginate @things
  = render @things
- else
  .alert-box No thingies to show :(

app/views/things/new.slim
h1 Create new thing

= simple_form_for @thing do |f|
  = f.input :content
  = f.submit class: 'button'

app/views/things/search.slim
h1 Search results

.alert-box.info.radius
  ' Use
  kbd -word
  '
  ' to skip things containing a given word. For example:
  kbd chrome -firefox
  '
  | will only find things mentioning chrome, but not firefox.
- if @things.any?
  = paginate @things
  = render @things
- else
  .alert-box We can't find any things using your query :(